"""Open, local-only primitives for evidence-backed video investigation."""

from .adapters import ActionSelector, ObservationAdapter, VisualMatcher
from .belief import (
    ActionUtilityWeights,
    BeliefConfig,
    action_allowed,
    compute_action_utility,
    select_best_action,
    shannon_entropy,
    update_beliefs,
)
from .evaluation import (
    CalibrationPrediction,
    GeolocationPrediction,
    RankedPrediction,
    RetrievalPrediction,
    binary_precision,
    expected_calibration_error,
    haversine_km,
    median_geolocation_error_km,
    multiclass_brier_score,
    ndcg_at_k,
    retrieval_recall_at_k,
    top_k_accuracy,
)
from .frames import (
    FrameDescriptor,
    FrameDescriptorProvider,
    FrameRejection,
    FrameRejectionReason,
    KeyframeSelection,
    KeyframeSelectionConfig,
    SelectionWeights,
    ShotBoundary,
    ShotDetector,
    information_score,
    perceptual_hash_distance,
    select_keyframes,
)
from .ipc import LocalRunExpectation, local_run_result_from_primitive, local_run_result_to_primitive
from .media import MediaMetadata, fingerprint_media, inspect_media, perceptual_hash, sha256_file
from .models import (
    ActionCandidate,
    ActionDecision,
    ActionType,
    AnalystDecision,
    AnalystDecisionKind,
    ArtifactRef,
    BeliefCandidate,
    BeliefSnapshot,
    CandidatePrior,
    ConnectivityPolicy,
    EgressDecision,
    EventCluster,
    EvidenceBatch,
    EvidenceContribution,
    EvidenceItem,
    EvidenceKind,
    Investigation,
    InvestigationKind,
    InvestigationStatus,
    InvestigationStep,
    JsonValue,
    Keyframe,
    ModelProvenance,
    SourceRecord,
    StepStatus,
    TraceEvent,
    TraceEventType,
    VerificationState,
    VisualMatch,
)
from .runner import DeterministicLocalRunner, LocalRunResult, StaticObservationAdapter
from .serialization import canonical_json, rfc3339, to_primitive
from .trace import TraceRecorder, read_trace_jsonl, validate_trace, write_trace_jsonl

__all__ = [
    "ActionCandidate",
    "ActionDecision",
    "ActionSelector",
    "ActionType",
    "ActionUtilityWeights",
    "AnalystDecision",
    "AnalystDecisionKind",
    "ArtifactRef",
    "BeliefCandidate",
    "BeliefConfig",
    "BeliefSnapshot",
    "CalibrationPrediction",
    "CandidatePrior",
    "ConnectivityPolicy",
    "DeterministicLocalRunner",
    "EgressDecision",
    "EventCluster",
    "EvidenceBatch",
    "EvidenceContribution",
    "EvidenceItem",
    "EvidenceKind",
    "GeolocationPrediction",
    "FrameDescriptor",
    "FrameDescriptorProvider",
    "FrameRejection",
    "FrameRejectionReason",
    "Investigation",
    "InvestigationKind",
    "InvestigationStatus",
    "InvestigationStep",
    "JsonValue",
    "Keyframe",
    "KeyframeSelection",
    "KeyframeSelectionConfig",
    "LocalRunExpectation",
    "LocalRunResult",
    "MediaMetadata",
    "ModelProvenance",
    "ObservationAdapter",
    "RankedPrediction",
    "RetrievalPrediction",
    "SelectionWeights",
    "ShotBoundary",
    "ShotDetector",
    "SourceRecord",
    "StaticObservationAdapter",
    "StepStatus",
    "TraceEvent",
    "TraceEventType",
    "TraceRecorder",
    "VerificationState",
    "VisualMatch",
    "VisualMatcher",
    "action_allowed",
    "binary_precision",
    "canonical_json",
    "compute_action_utility",
    "expected_calibration_error",
    "fingerprint_media",
    "haversine_km",
    "information_score",
    "inspect_media",
    "local_run_result_from_primitive",
    "local_run_result_to_primitive",
    "median_geolocation_error_km",
    "multiclass_brier_score",
    "ndcg_at_k",
    "perceptual_hash",
    "perceptual_hash_distance",
    "read_trace_jsonl",
    "retrieval_recall_at_k",
    "rfc3339",
    "select_best_action",
    "select_keyframes",
    "sha256_file",
    "shannon_entropy",
    "to_primitive",
    "top_k_accuracy",
    "update_beliefs",
    "validate_trace",
    "write_trace_jsonl",
]

__version__ = "0.1.0"
